# Generated by Django 5.2 on 2025-05-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='receiptfile',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='file_path',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='merchant_name',
            field=models.CharField(default='Unknown Merchant', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receipt',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receiptfile',
            name='file_path',
            field=models.CharField(max_length=1024),
        ),
    ]
